"""Serves the drift report generated by `scripts/generate_drift_report.py`."""

from pathlib import Path

from fastapi import APIRouter, Depends, HTTPException, status
from fastapi.responses import FileResponse

from api.common.auth import verify_basic_auth
from api.common.config import get_settings

router = APIRouter(prefix="/evidently", tags=["operations"])


@router.get(
    "",
    summary="Dernier rapport de drift",
    response_description="Rapport Evidently au format HTML",
    responses={
        200: {"content": {"text/html": {}}, "description": "Rapport Evidently au format HTML"},
        401: {"description": "Identifiants Basic manquants ou incorrects"},
        404: {"description": "Aucun rapport généré pour l'instant"},
    },
    include_in_schema=False,
)
def drift_report(_token: str = Depends(verify_basic_auth)) -> FileResponse:
    """Sert tel quel le rapport de dérive Evidently le plus récemment généré en CI.

    Protégé par HTTP Basic (`API_TOKEN`) — voir la page Sécurité de la
    documentation. 404 tant qu'aucun rapport n'a encore été déposé (voir
    `.github/workflows/drift-report.yml`).
    """
    report_path = Path(get_settings().reports_dir) / "drift_report.html"
    if not report_path.exists():
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND, detail="no drift report generated yet"
        )
    return FileResponse(report_path, media_type="text/html")
