"""Serves the drift report generated by `scripts/generate_drift_report.py`."""

from pathlib import Path

from fastapi import APIRouter, Depends, HTTPException, status
from fastapi.responses import FileResponse

from api.infra.auth import verify_basic_auth
from api.infra.config import get_settings

router = APIRouter(prefix="/evidently", tags=["operations"])


@router.get("", include_in_schema=False)
def drift_report(_token: str = Depends(verify_basic_auth)) -> FileResponse:
    """Return the most recently generated Evidently drift report.

    404 until the first CI run (see .github/workflows/drift-report.yml) has
    dropped a report into the reports directory.
    """
    report_path = Path(get_settings().reports_dir) / "drift_report.html"
    if not report_path.exists():
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND, detail="no drift report generated yet"
        )
    return FileResponse(report_path, media_type="text/html")
